### PR TITLE
Clone leak

### PR DESCRIPTION
**Pull request by jkour**
Can you please check the review? Thanks

### CODE REVIEW

**Comment by jkour** [comment]
You mentioned before that the event should be freed after the call to Post manually, correct? So, this fix is not required

**Comment by spinettaro** [comment]
Yes John, every subscriber must free his event, in order to avoid problems with memory management

**Comment by jkour** [comment]
For my MVVM setups, I've got a very similar framework with attributes etc (yours is of global scope-mine ties classes together) and I have solved this problem with the use of interfaces. If you declare a method like this: procedure myMethod (const aEvent: IInterface) then it becomes easy to manage objects.

But this means, interfaces must be used

**Comment by spinettaro** [comment]
Yes, but I don't like this approach. First because Delphi doesn't support generic with Interface and second because in this way every subscriber is responsible for memory management of his event (otherwise someone could free a data of event and a subscribe could have an invalid pointer )

**Pull request closed without merging**
