### PR TITLE
Further enhanced the code for allowing dynamic context.  Sticking to the principle "better be explicit than implicit",  created an enum TContextOption = (UseInstanceContext, UseAttributeContext). Updated testing case accordingly. This won't make the co...

### PR DESCRIPTION
**Pull request by wxinix**
...de overly complicated.

### CODE REVIEW

**Comment by wxinix** [comment]
@spinettaro @dkounal

Without making things too complicated than necessary, I created a new enum TContextOption = (UseInstanceContext, UseAttributeContext), to explicitly indicate the context, for example:
```
  TSubscriberWithInstanceContext = class(TBaseSubscriber)
    [Subscribe(Posting, UseInstanceContext)]
    procedure OnSimpleEventWithInstanceContext(AEvent: IEventBusEvent);
  end;
```
I also added new test cases and new exception type EUnspecifiedInstanceContext.  What do you think?  I think it is not necessary to make this overly complicated.

**Comment by dkounal** [comment]
I think that this is the best solution @wxinix Excellent work
Please forgive me but just a comment:
I notice that AContextOption is before AContext in the attribute. I believe that the opposite sequence will be better for compatibility of programs already using EventBus.

**Comment by wxinix** [comment]
> I notice that AContextOption is before AContext in the attribute. I believe that the opposite sequence will be better for compatibility of programs already using EventBus.

@dkounal  I think that is a very valid point, thank you for pointing that out.  I modified the constructor of TSubscriberAttribute class,  adding one new overloaded constructor:

```
// This is the original constructor, compatible with existing programs already using EventBus; internally defaults to UseAttributeContext
constructor Create(AThreadMode: TThreadMode = TThreadMode.Posting; const AContext: string = ''); overload;

// This is the new overloaded constructor    
constructor Create(AContextOption: TContextOption; AThreadMode: TThreadMode = TThreadMode.Posting; const AContext: string = ''); overload;
```

This way, existing code won't be affected. If a user would like to be explicit about TContextOption, he/she will be forced to specify TContextOption using the second constructor, for example:

```
  TSubscriberWithInstanceContext = class(TBaseSubscriber)
    [Subscribe(UseInstanceContext)]
    procedure OnSimpleEventWithInstanceContext(AEvent: IEventBusEvent);
  end;
```
What do you think?  This way, we will be very explicit and clear about the intention to use an instance context,  to be specified at run-time. Nobody will be confused (the developer or anyone reviewing the code at a later time).

**Comment by wxinix** [comment]
I close this and re-create a new one to have a clean slate.

**Pull request closed without merging**
